name: NontiaUHC
author: Sithey
version: 1.0
main: fr.sithey.uhc.Main
depend: [WorldEdit]
commands:
  saveinv:
  savedeath:
  specialsc:
  htp:
  hgamemode:
  hstop:
  hsay:
  hchat:
  hvote:
  hforce:
  hkick:
  hrez:
  hscoreboard:
  hmaxplayers:
  hwhitelist:
  oui:
  non:
  helpop:
  scenario:
  whitelist:
  sethost:
  rules:
    aliases:
      - uhc
      - config
  taupe:
  reveal:
  kit: